"""empty message

Revision ID: a19da61c6083
Revises: a30675376344
Create Date: 2025-06-27 23:26:03.486635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19da61c6083'
down_revision = 'a30675376344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_voter',
    sa.Column('user.id', sa.Integer(), nullable=False),
    sa.Column('question.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question.id'], ['question.id'], name=op.f('fk_question_voter_question.id_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user.id'], ['user.id'], name=op.f('fk_question_voter_user.id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user.id', 'question.id', name=op.f('pk_question_voter'))
    )
    op.create_table('answer_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer.id'], ['answer.id'], name=op.f('fk_answer_voter_answer.id_answer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_answer_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answer.id', name=op.f('pk_answer_voter'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_voter')
    op.drop_table('question_voter')
    # ### end Alembic commands ###
