"""empty message

Revision ID: f546d597da8b
Revises: a19da61c6083
Create Date: 2025-06-28 00:19:04.488938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f546d597da8b'
down_revision = 'a19da61c6083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_question_voter_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user.id')
        batch_op.drop_column('question.id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question.id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user.id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_question_voter_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_voter_question_id_question'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user.id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'question', ['question.id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('question_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
